version: "2"
checks:
  argument-count:
    config: 5
plugins:
  sonar-python:
    enabled: true
    checks:
      python:S107:
        enabled: false
  pep8:
    enabled: true
    checks:
      E128:  # continuation line uner-indented for visual indent
        enabled: false
      E221:  # multiple spaces before operator
        enabled: false
  radon:
    enabled: true
exclude_patterns:
  - "dist/"
  - "**/node_modules/"
  - "params/"
  - "docs/"
  - "original_codes/"
  - "**/__init__.py"
  - "**/*.md"
  - "**/*.in"
