permissions: read-all
name: pytest

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: get dependencies
        uses: ./.github/actions/get_dependencies

      - name: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        uses: ./.github/actions/test
